services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'
        exclude: '../tests/Behat/bootstrap.php'
